databases:
  - name: lanesraticket-db
    plan: free

services:
  - type: web
    name: lanesraticket
    runtime: docker
    plan: starter
    healthCheckPath: /
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: lanesraticket.onrender.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://lanesraticket.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: lanesraticket-db
          property: connectionString